apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustersecrets.clustersecret.io
spec:
  group: clustersecret.io
  names:
    kind: ClusterSecret
    plural: clustersecrets
    shortNames:
    - csec
    singular: clustersecret
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Secret Type
      jsonPath: .type
      name: Type
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          avoidNamespaces:
            items:
              type: string
            type: array
          data:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          matchNamespace:
            items:
              type: string
            type: array
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          type:
            type: string
        type: object
    served: true
    storage: true
