apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustersecrets.clustersecret.io
spec:
  group: clustersecret.io
  names:
    kind: ClusterSecret
    plural: clustersecrets
    shortNames:
    - csec
    singular: clustersecret
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Secret Type
      jsonPath: .type
      name: Type
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          avoidNamespaces:
            type: array
            items:
              type: string
          data:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          fromSecret:
            type: object
            properties:
              name:
                type: string
              namespace:
                type: string
              keys:
                type: array
                items:
                  type: string
            required:
            - name
            - namespace
          matchLabels:
            type: object
            additionalProperties:
              type: string
          matchNamespace:
            type: array
            items:
              type: string
          matchedSetsJoin:
            type: string
            description: intersection or union.  Operation to use when combining namespace sets from multiple labels or label and matchNamespace list
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          type:
            type: string
        oneOf:
        - required:
          - data
        - required:
          - fromSecret
    served: true
    storage: true
