apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-secret.fullname" . }}-account
  labels:
  {{- include "cluster-secret.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-secret.fullname" . }}-clustersecret
  labels:
    app: clustersecret
  {{- include "cluster-secret.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: clustersecret
    {{- include "cluster-secret.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: clustersecret
      {{- include "cluster-secret.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.clustersecret.clustersecret.image.repository }}:{{ .Values.clustersecret.clustersecret.image.tag | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        name: clustersecret
        resources: {}
      serviceAccountName: {{ include "cluster-secret.fullname" . }}-account
