apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-secret.fullname" . }}-account
  labels:
  {{- include "cluster-secret.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-secret.fullname" . }}-clustersecret
  labels:
    app: clustersecret
  {{- include "cluster-secret.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: clustersecret
    {{- include "cluster-secret.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: clustersecret
      {{- include "cluster-secret.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 100 # 100 is set by the container and can NOT be changed here - this would result in a getpwuid() error
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        - name: CLUSTER_SECRET_VERSION
          value: {{ .Chart.AppVersion | quote }}
        - name: REPLACE_EXISTING
          value: {{ .Values.replace_existing | default "false" | quote }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag  | default .Chart.AppVersion }}
        name: clustersecret
        securityContext:
          runAsUser: 100 # 100 is set by the container and can NOT be changed here - this would result in a getpwuid() error
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 120
        resources: {}
      serviceAccountName: {{ include "cluster-secret.fullname" . }}-account
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}