name: Lint
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Python Code Quality and Lint
        # You may pin to the exact commit or the version.
        # uses: ricardochaves/python-lint@32032eca67291cd71f88d79e61bc4b904ee03265
        uses: ricardochaves/python-lint@v1.3.0
        with:
          # A list of all paths to test
          python-root-list: # optional, default is .
          # Use Pylint
          use-pylint: # optional, default is true
          # Use pycodestyle
          use-pycodestyle: # optional, default is true
          # Use Flake8
          use-flake8: # optional, default is true
          # Use Black
          use-black: # optional, default is true
          # Use mypy
          use-mypy: # optional, default is true
          # Use isort
          use-isort: # optional, default is true
          # Extra options: pylint $(extra-pylint-options) $(python-root-list)
          extra-pylint-options: # optional, default is 
          # Extra options: pycodestyle $(extra-pycodestyle-options) $(python-root-list)
          extra-pycodestyle-options: # optional, default is 
          # Extra options: flake8 $(extra-flake8-options) $(python-root-list)
          extra-flake8-options: # optional, default is 
          # Extra options: black --check $(extra-black-options) $(python-root-list)
          extra-black-options: # optional, default is 
          # Extra options: mypy $(extra-mypy-options) $(python-root-list)
          extra-mypy-options: # optional, default is 
          # Extra options: isort -rc $(extra-isort-options) $(python-root-list) -c --diff 
          extra-isort-options: # optional, default is 
